version: '2'
services:
  frontend:
    build:  ./frontend
    command: yarn start
    volumes:
      - ./frontend:/usr/src/app/
      - ./frontend/node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
  server:
    build:  ./server
    command: yarn start
    volumes:
      - ./server:/usr/src/app/
      - ./server/node_modules:/usr/app/node_modules
    ports:
      - "4000:4000"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker